"""First Migration

Revision ID: b41052e874b9
Revises:
Create Date: 2024-05-28 19:23:58.770569

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b41052e874b9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="my_study_api",
    )
    op.create_index(
        op.f("ix_my_study_api_decks_id"),
        "decks",
        ["id"],
        unique=False,
        schema="my_study_api",
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("side_a", sa.String(), nullable=True),
        sa.Column("side_b", sa.String(), nullable=True),
        sa.Column("next_review_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["my_study_api.decks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="my_study_api",
    )
    op.create_index(
        op.f("ix_my_study_api_cards_id"),
        "cards",
        ["id"],
        unique=False,
        schema="my_study_api",
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("easiness", sa.Float(), nullable=True),
        sa.Column("interval", sa.Integer(), nullable=True),
        sa.Column("repetitions", sa.Integer(), nullable=True),
        sa.Column("review_date", sa.Date(), nullable=True),
        sa.Column("quality", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["my_study_api.cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="my_study_api",
    )
    op.create_index(
        op.f("ix_my_study_api_reviews_id"),
        "reviews",
        ["id"],
        unique=False,
        schema="my_study_api",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_my_study_api_reviews_id"), table_name="reviews", schema="my_study_api"
    )
    op.drop_table("reviews", schema="my_study_api")
    op.drop_index(
        op.f("ix_my_study_api_cards_id"), table_name="cards", schema="my_study_api"
    )
    op.drop_table("cards", schema="my_study_api")
    op.drop_index(
        op.f("ix_my_study_api_decks_id"), table_name="decks", schema="my_study_api"
    )
    op.drop_table("decks", schema="my_study_api")
    # ### end Alembic commands ###
