"""Insert Card description

Revision ID: c98a384c9940
Revises: ef6ce0fba8b6
Create Date: 2024-05-22 10:03:00.081926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98a384c9940'
down_revision: Union[str, None] = 'ef6ce0fba8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'description')
    # ### end Alembic commands ###
